name: plant_inventory
description: A simple plant inventory app
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core data + local DB
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.5
  path: ^1.9.1

  # Media & files
  image_picker: ^1.2.0
  file_selector: ^1.0.3
  mime: ^2.0.0
  image: ^4.2.0

  # UI / charts / env
  fl_chart: ^0.68.0
  flutter_dotenv: ^5.1.0
  excel: ^4.0.2   # create .xlsx files in pure Dart
  package_info_plus: ^8.0.0
  shared_preferences: ^2.3.2

  # Supabase (keep what you already have if added)
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  windows: true
  macos: true
  image_path: "lib/assets/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
  - .env
  - lib/assets/logo.png